version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
          - node_modules-{{ checksum "yarn.lock" }}
          - node_modules-
      - run:
          name: install
          command: yarn install
      - save_cache:
          key: node_modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: test
          command: yarn test
